version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      typescript:
        patterns:
          - "@voxpelli/tsconfig"
          - "@types/node"
          - "typescript"
      preact:
        patterns:
          - "@preact/signals"
          - "preact"
          - "preact-render-to-string"
          - "htm"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
