name: npm bump

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version type'
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
          - from-git
          - custom
        default: 'patch'
        required: true
      new-version:
        description: 'Custom version (only used when version-type is "custom")'
        required: false
      preid:
        description: 'Prerelease identifier (used with premajor, preminor, prepatch, or prerelease)'
        type: choice
        options:
          - ''
          - alpha
          - beta
          - rc
        required: false
      dist-tag:
        description: 'npm distribution tag'
        type: choice
        options:
          - latest
          - beta
        default: 'latest'
        required: true

env:
  FORCE_COLOR: 3

permissions:
  contents: write
  id-token: write

concurrency:
  group: npm-bump
  cancel-in-progress: true

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    outputs:
      tagName: ${{ steps.npm-bump.outputs.release-tag }}
    steps:
    - uses: actions/checkout@v7
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v7
      with:
        node-version-file: package.json
        check-latest: true
    - run: npm i
    - run: npx playwright install --with-deps chromium
    - run: npm test
    - run: git reset --hard && git clean -fd
    - name: Version and publish to npm
      id: npm-bump
      uses: bcomnes/npm-bump@v3.0.4
      with:
        version-type: ${{ github.event.inputs['version-type'] }}
        new-version: ${{ github.event.inputs['new-version'] }}
        preid: ${{ github.event.inputs['preid'] }}
        dist-tag: ${{ github.event.inputs['dist-tag'] }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
